apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:02:52Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "307494"
  uid: 65d9d814-622b-4e3f-803d-db2816446986
spec:
  clusterIP: 10.233.1.49
  clusterIPs:
  - 10.233.1.49
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30553
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
